### ISSUE TITLE
Your image was not uploaded

### ISSUE THREAD

**Issue by mrhydra-np** [digininja/DVWA#397] opened 2020-10-21 06:39 UTC
When i try to upload anything it says your image was not uploaded. can i get a suggestion 😂

**Comment by digininja** [comment] 2020-10-21 06:56
Try a smaller file and check directory permissions

**Comment by mrhydra-np** [comment] 2020-10-21 11:03
I tried with 100kb file again got same error and where can i check directory permissions? Cant find it ![image](https://user-images.githubusercontent.com/73021341/96711413-62288200-1352-11eb-8dbd-0d94f04e8a24.jpeg)

**Comment by digininja** [comment] 2020-10-21 11:06
Do some research on either Linux or Windows directory permissions. The README tells you where the directory is.

**Comment by digininja** [comment] 2020-10-31 20:58
Any further updates before the issue is closed?

**Comment by digininja** [comment] 2020-11-03 10:17
closing due to lack of updates.

**Closed by digininja** 2020-11-03 10:17 UTC
